### ISSUE TITLE
How about changing to Windows 10?

### ISSUE THREAD

**Issue by ipepe** [ecalder6/azure-gaming#15]
I propose change to Windows 10:
```json
{"imageReference": {
    "publisher": "MicrosoftWindowsDesktop",
    "offer": "Windows-10",
    "sku": "rs4-pro",
    "version": "latest"
}}
```

**Comment by ecalder6** [comment]
Can an individual deploy a Windows 10 VM? I was under the impression that you have to own a professional/enterprise subscription of Windows.

If it can be done I'd be more than happy to change it.

**Comment by ipepe** [comment]
Honestly, I am not sure, because I have MSDN license. But there are at least few Windows 10/8/7 imageReferences

**Comment by ecalder6** [comment]
Is that connected to your Azure subscription?

**Comment by ipepe** [comment]
Yes, I have MSDN Azure subscription

**Comment by ecalder6** [comment]
Ok cool. For a regular paid subscription you may not be able to deploy a Windows 10 VM. I'll dig into it if I get a chance.

**Comment by ecalder6** [comment]
![image](https://user-images.githubusercontent.com/8675242/44951932-a250e180-ae26-11e8-9a44-5f8591a88882.png)

I don't think you can use it unless you have a professional subscription.

**Comment by jostidetosti** [comment]
@ecalder6 Where did you find this information? I deployed an instance with Windows 10 Pro this week and I don't recall seeing a message like in your screenshot. Though it's entirely possible I just missed it!

I use 'Azure for Students' btw.

**Comment by ecalder6** [comment]
You should see the message when you select Windows 10:
![image](https://user-images.githubusercontent.com/8675242/56056303-9f00cb00-5d10-11e9-9a58-2e0e161ba300.png)

**Comment by jostidetosti** [comment]
Okay, another reason not to use Windows 10 [from here](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/n-series-driver-setup):

![aaa](https://i.imgur.com/63so5Si.png)

Seems you can only use the Tesla GPU on Windows server.

**Comment by ecalder6** [comment]
You want to get the [GRID drivers](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/n-series-driver-setup#nvidia-grid-drivers), which support Windows 10.
