### ISSUE TITLE
Disk and OS question

### ISSUE THREAD

**Issue by jasbryan** [ecalder6/azure-gaming#23]
Great set of tools BTW. This is my third build with some internet provided instructions and this one seems to be working well. Although I can't get steam clients to see each other.

I had 2 quick Qs:
1.Why did you choose the standard HDD instead of the SSD?
2.Why did you choose to use windows server instead of Windows10 image?

Thanks

**Comment by ecalder6** [comment]
1. At the time this was written, SSD wasn't an option for NV series VMs. The support for SSD was released in last September: https://azure.microsoft.com/en-us/updates/public-preview-new-gpu-enabled-nvv2-azure-vms-for-graphics-intensive-applications/. This should be added as an option but unfortunatley I haven't had the chance to test it. Feel free to submit a PR to add it :)

2. I believe Windows 10 image can only be used if you have a valid professional subscription that gives Windows 10 licenses. See #15 for more.

**Comment by jasbryan** [comment]
I have created a PR for the OSdisk change. I have not tested it out though. I will try and do it later if I can.
https://github.com/ecalder6/azure-gaming/pull/24
