### ISSUE TITLE
evictionPolicy?

### ISSUE THREAD

**Issue by mulat666** [ecalder6/azure-gaming#26]
Hi
After deleting VM I've lost whole setup. What do you think to change "evictionPolicy" to "deallocate"?

**Comment by ecalder6** [comment]
Good thought! The only problem is that de-allocated VMs may not come back according to the [documentation](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-low-priority#eviction-policy). Still I'd imagine it's better than delete by default. Feel free to submit a PR to change it!
