### ISSUE TITLE
Standard_NV6_Promo instead of default

### ISSUE THREAD

**Issue by tofujisawa** [ecalder6/azure-gaming#32]
Hi,

I have successfully deployed my gaming PC on Azure thanks to script here.
One thing I noticed is in my region (Japan east) Standard_NV6 is not available but Promo version is available. So I replaced VM size to Standard_NV6_Promo and the script worked.

It is great if the script detects either one of two or if you can update README.

Thanks.

**Comment by ecalder6** [comment]
Thanks for the heads up! I'll take a look into NV6_Promo.
