### ISSUE TITLE
VM from template - nvidia driver not properly installed

### ISSUE THREAD

**Issue by fanoush** [ecalder6/azure-gaming#36]
Yesterday I deployed NV6 directly from the template link - single VM, standard (not spot), after coming up there was Steam and zerotier properly installed however there was no disconnect shortcut on desktop. So I made it myself but even after changing 2 to 1 or vice versa so that it disconnected me when clicking it, steamlink connection showed microsoft driver and everything was slow. also the custom extension in portal showed some error messages related to nvidia driver. Looks like it was  expected in some 2nd level path on C: but it was actually deeply nested in like 5 folders. Anyway I rerun it in same way (with silent noreboot flags) then rebooted  and it didn't help. So I run some stuff semi-randomly from setup and setup2 (like e.g. disable hyperv driver) rebooted again and now it finally works great.
 
So just a report that it failed out of box for me yesterday. Maybe current nvidia driver is extracted into wrong location/has different folder structure than expected?

Oh, one more thing, there was no NSG set for the VM networking so the RDP port  was open to whole world without any hint anywhere in portal. So might be better to include NSG in  the template just so that people see more clearly the rdp port is open to whole world and may secure it properly or even disable it completely when using zerotier.

BTW I was using this like year ago with low priority VM scaleset and it worked great but now with spot instances this is so unstable I went for normal VM now. Actually I didn't use it few months and the scaleset was somehow automatically converted by MS from low priority VM to spot instance version with policy set as delete(!). So yesterday I started it for the first time after months and  was playing some game and it suddenly disconnected an I only managed to see 'deleting' in portal and whole vm was gone! Only then I noticed the policy of course. I also had other non-steam games there so lost many save games progress this way :-(

Anyway thanks for this, I am using steamlink from raspberry pi with this and enjoy absolutely quiet high quality gaming :-) Well sometimes I die because of sudden lag spike but it is not that bad.

**Comment by ecalder6** [comment]
I'll look into using the [Nvidia Driver Extension](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/hpccompute-gpu-windows), which should be much more reliable. Unfortunately there's not much you can do for low priority VM eviction. You _could_ subscribe to [Scheduled Events](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/spot-vms), but it will only give you a 30 seconds heads up and you have to continuously pull the endpoint.
