### ISSUE TITLE
Connect/Disconnect Issue

### ISSUE THREAD

**Issue by levalencia** [ecalder6/azure-gaming#37]
Hello, I already sent you an email but I will post it here anyway.

I also have a macbook pro with low specs, and for gaming its not ideal, the game I am trying to stream is Cities Skylines, which I guess should use less CPU/GPU/Network than a FPS game like overwatch.

I created the VM with the Azure button, the VPN is setup and both machines are joined.

1. I supposed that the VM is already configured with everything from your guide, except the Steam Server settings., so I read your guide but I only applied the Steam Host Settings.
2. I applied the steam client settings.

when I click on Connect, the game starts and I can see a game splash screen, then it disconnects immediately.

Not sure what I am missing here.

Thanks

**Comment by csm10495** [comment]
I basically see the same thing. Except I'm on Windows on both sides and am trying with CS:GO.

**Comment by ecalder6** [comment]
Try Moonlight, Parsec, or Rainway if you are having trouble with Steam streaming.

**Comment by AmineI** [comment]
Please try to use C:/disconnect.lnk as specified and retry to connect. The behavior you mentions does happen if you don't, but it may be another issue you're facing, so it'd be helpful if you could report your results
