### ISSUE TITLE
Steam game showing display adapter "microsoft basic display adapter"

### ISSUE THREAD

**Issue by TobiasHeck** [ecalder6/azure-gaming#49]
Hi @ecalder6 ,
first of all thank you for this guide!

I created the VM myself, instead of using your script, but implemented all the steps anyways.
Whenever I start Total War Warhammer 2 in steam via remote play, the display adapter is showing as "microsoft basic display adapter" and not as nvidia.
Any idea why and how to solve that?

**Comment by ecalder6** [comment]
This happens when either GRID driver is not installed correctly or Microsoft Hyper-V Video isn't disabled. Also check if TCC is disabled. See the utils.psm1 script for more details.

**Comment by TobiasHeck** [comment]
Thanks for taking the time to respond!
I did check all of these settings, and they were all correct.
At the end, I just created a new VM and it worked there ;-)
