### ISSUE TITLE
Link to VBCable should be updated

### ISSUE THREAD

**Issue by vladiliescu** [ecalder6/azure-gaming#53]
Hi there, I've noticed the old link to the audio driver (http://vbaudio.jcedeveloppement.com/Download_CABLE/VBCABLE_Driver_Pack43.zip) doesn't work anymore, which means sound won't work on newly installed machines (or I couldn't get it to work :) ).

Googling a bit, it looks like the link below is a good alternative:
https://download.vb-audio.com/Download_CABLE/VBCABLE_Driver_Pack43.zip

**Comment by AmineI** [comment]
Great catch. Just made a commit to update this link in the powershell utils file, thanks !

Unfortunately, until I do some testing (which might be in a long time), I can't confirm this works. I don't see why it shouldn't though, so I'll submit a PR.

**Comment by ecalder6** [comment]
Thanks for the issue and the PR. I wonder if this is still needed. I believe Steam will install an audio driver by default.

**Comment by vladiliescu** [comment]
When I had opened this issue it didn't install any audio driver, if it does now then they've updated it in the meantime :). I remember having to dig in a bit through the scripts to debug this, having Steam install that for me would have been great.
