### ISSUE TITLE
Tried creating a VM with NVv4-series, and it works great! Except that I can't get audio functioning properly.

### ISSUE THREAD

**Issue by RobertPakko** [ecalder6/azure-gaming#54]
Anyone else have audio issues?

I made sure to enable the "Play audio on Host" setting but it has not resolved the issue. Would be very grateful if anyone found a solution.

In case it is relevant. Audio does seem to work if I'm simply using remote desktop, but of course the streaming performance is worse.

**Comment by tnathanp** [comment]
Do you have trouble logging in to Geforce Experience?
